#!/bin/zsh

if [ $# -ne 1 ]; then
    echo "usage: $0 filename"
else
    filename=$(basename "$1")
    g++ -Wall -Wextra -fno-asynchronous-unwind-tables -S -O0 ${filename%.*}.cpp && printf 'Wrote %s successfully.\n' "${filename%.*}."[sS]
    # this will include cfi labels and optimization
    #gcc -Wall -Wextra -ggdb -std=c99 -S ${filename%.*}.c && printf 'Wrote %s successfully.\n' "${filename%.*}."[sS]
fi
