#!/bin/zsh

# Stops after the stage of compilation proper; does not assemble.  The output
# is in the form of an assembler code file.
#
# Does not optimize.

if [ $# -ne 1 ]; then
    echo "usage: $0 filename"
else
    filename=$(basename "$1")
    gcc -Wall -Wextra -fno-asynchronous-unwind-tables -std=c99 -S -O0 ${filename%.*}.c

    # this will include cfi labels and optimization
    #gcc -Wall -ggdb -std=c99 -S ${filename%.*}.c

    if [[ -n `find . -name ${filename%.*}.S` ]]; then
        echo "Wrote ${filename%.*}.S successfully."
    elif [[ -n `find . -name ${filename%.*}.s` ]]; then
        echo "Wrote ${filename%.*}.s successfully."
    fi
fi
