#!/bin/sh

# Attempts to compile and run the Java program provided in the command-line
# argument.  If successful, the produced class file will be run with the
# remaining command-line arguments, and then the script will delete the
# associated class file.

if [ $# -lt 1 ]; then
    echo "usage: $0 filename arg1 arg2 .."
else
    filename=$(basename "$1")
    shift
    javac ${filename%.*}.java && java ${filename%.*} $@ && rm ${filename%.*}.class
fi
