#!/bin/bash

if [ $# -ne 1 ]; then
    echo "usage: $0 filename"
else
    gcc -Wall -ggdb -std=c99 -c ${1%%.*}.c && gcc -Wall -ggdb -std=c99 -o ${1%%.*} ${1%%.*}.o && ./${1%%.*} && rm ${1%%.*}{,.o}
fi
