#!/bin/bash

if [ $# -ne 1 ]; then
    echo "usage: $0 filename"
else
    filename=$(basename "$1")
    gcc -Wall -ggdb -std=c99 -c ${filename%.*}.c && gcc -Wall -ggdb -std=c99 -o ${filename%.*} ${filename%.*}.o && ./${filename%.*} && rm ${filename%.*}{,.o}
fi
