#!/bin/zsh

if [ $# -ne 1 ]; then
    echo "usage: $0 filename"
else
    filename=$(basename "$1")
    g++ -Wall -ggdb -c ${filename%.*}.cpp && g++ -Wall -ggdb -o ${filename%.*} ${filename%.*}.o && ./${filename%.*} && rm ${filename%.*}{,.o}
fi
