#!/bin/sh

if [ $# -lt 1 ]; then
    echo "usage: $0 filename arg1 arg2 .."
else
    filename=$(basename "$1")
    shift
    g++ -Wall -Wextra -ggdb -c ${filename%.*}.cpp && g++ -Wall -Wextra -ggdb -o ${filename%.*} ${filename%.*}.o && ./${filename%.*} $@ && rm ${filename%.*}{,.o}
fi
